/** @type {import('jest').Config} */
export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: ['**/__tests__/**/*.test.ts'],
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: 'tsconfig.json',
      },
    ],
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@polymarket/strategy$': '<rootDir>/../../packages/application/strategy/src/index.ts',
    '^@polymarket/timestamp$': '<rootDir>/../../packages/foundation/timestamp/src/index.ts',
    '^@polymarket/value-objects$': '<rootDir>/../../packages/domain/value-objects/src/index.ts',
    '^@polymarket/value-objects/balance$': '<rootDir>/../../packages/domain/value-objects/src/balance/index.ts',
    '^@polymarket/value-objects/money$': '<rootDir>/../../packages/domain/value-objects/src/money/index.ts',
    '^@polymarket/value-objects/signed-quantity$': '<rootDir>/../../packages/domain/value-objects/src/signed-quantity/index.ts',
    '^@polymarket/ids$': '<rootDir>/../../packages/foundation/ids/src/index.ts',
    '^@polymarket/ports$': '<rootDir>/../../packages/application/ports/src/index.ts',
    '^@polymarket/event-bus$': '<rootDir>/../../packages/application/event-bus/src/index.ts',
    '^@polymarket/messages$': '<rootDir>/../../packages/foundation/messages/src/index.ts',
    '^@polymarket/message-bus$': '<rootDir>/../../packages/foundation/message-bus/src/index.ts',
    '^@polymarket/application-events$': '<rootDir>/../../packages/application/events/src/index.ts',
    '^@polymarket/order-events$': '<rootDir>/../../packages/domain/events/order/src/index.ts',
    '^@polymarket/result$': '<rootDir>/../../packages/foundation/result/src/index.ts',
    '^@polymarket/errors$': '<rootDir>/../../packages/foundation/errors/src/index.ts',
    '^@polymarket/errors/(.*)$': '<rootDir>/../../packages/foundation/errors/src/$1/index.ts',
    '^@polymarket/logger$': '<rootDir>/../../packages/foundation/logger/src/index.ts',
    '^@polymarket/time$': '<rootDir>/../../packages/foundation/time/src/index.ts',
    '^@polymarket/math$': '<rootDir>/../../packages/foundation/math/src/index.ts',
    '^@polymarket/rolling-window$': '<rootDir>/../../packages/foundation/rolling-window/src/index.ts',
    '^@polymarket/order$': '<rootDir>/../../packages/domain/entities/order/src/index.ts',
    '^@polymarket/portfolio$': '<rootDir>/../../packages/domain/entities/portfolio/src/index.ts',
    '^@polymarket/market$': '<rootDir>/../../packages/domain/entities/market/src/index.ts',
    '^@polymarket/position$': '<rootDir>/../../packages/domain/entities/position/src/index.ts',
    '^@polymarket/trade-tape$': '<rootDir>/../../packages/domain/market-data/trade-tape/src/index.ts',
    '^@polymarket/orderbook$': '<rootDir>/../../packages/domain/entities/orderbook/src/index.ts',
    '^@polymarket/value-objects/asset-quantity$': '<rootDir>/../../packages/domain/value-objects/src/asset-quantity/index.ts',
    '^@polymarket/fill$': '<rootDir>/../../packages/domain/entities/fill/src/index.ts',
    '^@polymarket/fill/polymarket-fee$': '<rootDir>/../../packages/domain/entities/fill/src/polymarket-fee.ts',
    '^@polymarket/ledger$': '<rootDir>/../../packages/domain/accounting/ledger/src/index.ts',
    '^@polymarket/trade$': '<rootDir>/../../packages/domain/entities/trade/src/index.ts',
    '^@polymarket/use-cases$': '<rootDir>/../../packages/application/use-cases/src/index.ts',
    '^@polymarket/backtesting$': '<rootDir>/../../packages/infrastructure/backtesting/src/index.ts',
    '^@polymarket/cross-market$': '<rootDir>/../../packages/domain/cross-market/src/index.ts',
    '^@polymarket/in-memory$': '<rootDir>/../../packages/infrastructure/in-memory/src/index.ts',
    '^@polymarket/snapshot-readers$': '<rootDir>/../../packages/infrastructure/persistence/snapshot-readers/src/index.ts',
    '^@polymarket/handlers$': '<rootDir>/../../packages/application/handlers/src/index.ts',
    '^@polymarket/market-state$': '<rootDir>/../../packages/application/market-state/src/index.ts',
    '^@polymarket/risk$': '<rootDir>/../../packages/application/risk/src/index.ts',
  },
};
